### ISSUE TITLE
AOTT Raise Implementation

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#234]
**Description**
Given a set of meaning types with values (Semstring, Type, Variable Name, Value) create a Meaning (Prompt). Have a Set of Parameters (info, except, reason).

**Todos**
- [x] Decide on How the Prompt will be Decided
- [x] Decide on How we pass the Meaning Types
- [x] Decide on what Parameters Available.
- [ ] How we include Jac Code Constructs like Nodes Graphs Edges
- [x] Decide on the Representation of Different Constructs (ENUM, ....)
- [ ] Create JAC/Python
- [ ] Write unit tests to ensure AOTT Raise is working correctly
- [ ] Update documentation to include information about AOTT Raise and how to use it
