### ISSUE TITLE
AOTT Lower Implementation

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#235]
**Description**
Convert the Meaning Out from the LLM into the output format needed, while keeping track of other variables (reason, etc.).

**Todos**
- [ ] Meaning + Output Type --> Primary Objects (Str, Int, Floats etc...)
- [ ] Meaning + Output Type --> Objects Defined (Node, Edges, Graphs, Objects, ENUM ...)
- [ ] Decide on How to provide debugging outputs with the Output
